### ISSUE TITLE
a weaving recipe conflict with default minetest_game

### ISSUE THREAD

**Issue by Trokinos** [DokimiCU/earthbuild#5]
At the time i am writing this , in your mod , in weaving.lua

minetest.register_craft({
	output = 'earthbuild:woven_mat',
	recipe = {
		{'', '', ''},
		{'', '', ''},
		{'default:papyrus', 'default:papyrus', 'default:papyrus'},
	}
})

is conflicting with 
minetest.register_craft({
	output = 'default:paper',
	recipe = {
		{'default:papyrus', 'default:papyrus', 'default:papyrus'},
	}
})

that can  be found in ...\games\minetest_game\mods\default

**Comment by DokimiCU** [comment]
recipe will be removed in next update
